### PR TITLE
Update index.js for export nunjucks

### PR DESCRIPTION
**Pull request by 625781186**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why?

**Comment by binyamin** [comment]
Do we really need to export the entire nunjucks library? From the users' perspectives, it might make more sense to export a function which returns an instance of `nunjucks.Environment`. I was originally going to suggest this as a fix for #42 (custom tags).

```js
module.exports.createEnvironment = function createEnvironment(searchPaths, options) {
    return new nunjucks.Environment(new nunjucks.FileSystemLoader(searchPaths), options);
}
```

**Comment by sindresorhus** [comment]
@binyamin Isn't this already possible with the `env` option?

**Comment by sindresorhus** [comment]
Closing this PR for lack of activity.

**Pull request closed without merging**
